services:
  resume-app:
    build: .
    volumes:
      - ./my-resume:/app
    stdin_open: true
    tty: true
    working_dir: /app/
    ports:
    - 3000:3000
    command: sh -c "npm install && npm start"